#!/usr/bin/env bash
set -e

while read filename ; do
  ln -s "$HOME/.dotfiles/$filename" "$HOME/$filename" || true
done <<END
.bash_profile
.bashrc
.gitconfig
.inputrc
.iterm
.ssh/config
.vimrc
git
END
