#!/usr/bin/env bash

usage() {
  echo "usage: $(basename $0)"
  echo
  echo "Open the current Git repository in a browser."
}

case "$1" in
  -h|--help) usage;;
  -*) echo "invalid argument $1" 1>&2;;
  *) open "https://github.com/$(git ls-remote --get-url | sed 's/^.*:\(.*\)[.]git$/\1/')/commits/$(git rev-parse --abbrev-ref HEAD)";;
esac
