#!/usr/bin/env bash

usage() {
  echo "
  usage: $(basename $0) [options]

  Open the current Git repository in a browser.

  options:

    --default-branch <branch-name>
"
}

project_slug=$(git ls-remote --get-url | sed -E 's!^([^@]*@[^:]*:|https://[^/]*/)([^/]*/[^/]*)[.]git$!\2!')
default_branch=master
current_branch=$(git rev-parse --abbrev-ref HEAD)
case "$1" in
  -h|--help) usage ; exit ;;
  --default-branch) default_branch="$2" ;;
  -*) echo "invalid argument $1" >&2 ; exit 1 ;;
esac
if [ "$current_branch" = "$default_branch" ] ; then
  open "https://github.com/$project_slug/commits/$default_branch"
else
  open "https://github.com/$project_slug/compare/$default_branch...$current_branch"
fi
